### ISSUE TITLE
Add llvm compiler and clang 14 

### ISSUE THREAD

**Issue by ghost** [lemniskett/android-kernel-actions#7]
Thanks

**Comment by mmdlsu** [comment]
Only need to modify the entrypoint.sh
`https://github.com/mmdlsu/android-kernel-actions/blob/master/entrypoint.sh`

**Comment by mmdlsu** [comment]
`apt install -y  sudo software-properties-common gpg-agent `
 `wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -`
`sudo add-apt-repository -y "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main"`

**Comment by lemniskett** [comment]
Done, check out version `v1.0.0`
